title: Lester Tan
owner: Lester Tan
email:
description: Software Engineer
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://lester.sh" # the base hostname & protocol for your site, e.g. http://example.com
language: en
twitter_username:
github_username:
disqus_username: 
# Build settings
markdown: kramdown
theme: minima
excerpt_separator: <!--more-->

permalink: /:year/:month/:day/:title/

plugins:
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-seo-tag

exclude:
  - Gemfile
  - Gemfile.lock
  - vendor/bundle
  - README.md
  - LICENSE.txt
  - contact.md
  - blog.md
  - projects.md
  - categories.md
  - _posts/*
  - categories/*
