title: Lester Tan
owner: Lester Tan
description: Lester Tan - Software Engineer - online resume
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://lester.sh" # the base hostname & protocol for your site, e.g. http://example.com
language: en

# Build settings
markdown: kramdown
theme: minima
excerpt_separator: <!--more-->

author:
  name: Lester Tan
  type: Person

social:
  name: Lester Tan
  links:
    - https://github.com/lestertj
    - https://www.linkedin.com/in/lestertj

permalink: /:year/:month/:day/:title/

plugins:
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-seo-tag

exclude:
  - Gemfile
  - Gemfile.lock
  - vendor/bundle
  - README.md
  - LICENSE.txt
  - contact.md
  - blog.md
  - projects.md
  - categories.md
  - _posts/*
  - categories/*
